# Generated by Django 4.2.16 on 2024-09-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_catagory', models.CharField(max_length=250)),
                ('a_title', models.CharField(max_length=80)),
                ('a_authorname', models.CharField(max_length=100)),
                ('a_date', models.DateField()),
                ('a_description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='#', upload_to='article_img/')),
            ],
        ),
    ]
