# Generated by Django 4.2.16 on 2024-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_title', models.CharField(max_length=80)),
                ('trending_date', models.DateField()),
                ('trending_image', models.ImageField(default='#', upload_to='trending_img/')),
            ],
        ),
    ]
