# Generated by Django 4.2.16 on 2024-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=80)),
                ('about_description', models.CharField(max_length=600)),
                ('about_pofile_image', models.ImageField(default='#', upload_to='about_img/')),
                ('about_cover_image', models.ImageField(default='#', upload_to='about_img/')),
            ],
        ),
    ]
